/**
 * DOCX Image Extractor (Mammoth Fallback)
 *
 * Extracts images from HTML generated by mammoth.js fallback.
 * Only used when styled parser is not available.
 *
 * @module docx/extractors/images
 */

import { createRequire } from 'module';
import type { DocxImage } from '../types.js';

const require = createRequire(import.meta.url);
const { DOMParser } = require('@xmldom/xmldom');

/**
 * Extract base64-encoded images from HTML (mammoth.js fallback only).
 * Returns empty array if parsing fails.
 */
export function extractImagesFromHtml(html: string): DocxImage[] {
  const images: DocxImage[] = [];
  try {
    const doc = new DOMParser().parseFromString(html, 'text/html');
    const imgElements = doc.getElementsByTagName('img');

    for (let i = 0; i < imgElements.length; i++) {
      const src = imgElements[i].getAttribute('src') || '';
      const alt = imgElements[i].getAttribute('alt') || '';
      const match = src.match(/^data:([^;]+);base64,(.+)$/);
      if (match) {
        images.push({
          id: `img_${i}`,
          data: match[2],
          mimeType: match[1],
          altText: alt || undefined,
          originalSize: Buffer.from(match[2], 'base64').length,
        });
      }
    }
  } catch {
    // Non-critical
  }
  return images;
}

