# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

ENV MCP_CLIENT_DOCKER=true

LABEL io.docker.server.metadata='{ \
    "name": "desktop-commander", \
    "version": "1.0.0", \
    "description": "Desktop Commander MCP Server", \
    "command": ["node", "dist/index.js"], \
    "mounts": [ \
    { \
    "source": "/var/run/docker.sock", \
    "target": "/var/run/docker.sock", \
    "type": "bind" \
    }, \
    { \
    "source": "/Users/dasein/Documents", \
    "target": "/home/Documents", \
    "type": "bind" \
    } \
    ] \
    }'
# 🔥 INSTALL DOCKER CLI + COMPOSE
RUN apk add --no-cache \
    docker-cli \
    docker-cli-compose \
    bash

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without triggering any unwanted scripts
RUN npm install --ignore-scripts

# Run post-install script for @vscode/ripgrep to download the binary
RUN npm rebuild @vscode/ripgrep

# Copy all source code
COPY . .

# Build the application
RUN npm run build

# Set default command (can be overridden by metadata)
CMD ["node", "dist/index.js"]

